import express from 'express';
const route = express.Router();

route.get("/gen2",function(req,res){
    const pokemon2 = [
        {dex: 152, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0152_f00_s0.png", nome: "Chikorita", tipo: "Planta"},
        {dex: 153, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0153_f00_s0.png", nome: "Bayleef", tipo: "Planta"},
        {dex: 154, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0154_f00_s0.png", nome: "Meganium", tipo: "Planta"},
        {dex: 155, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0155_f00_s0.png", nome: "Cyndaquil", tipo: "Fogo"},
        {dex: 156, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0156_f00_s0.png", nome: "Quilava", tipo: "Fogo"},
        {dex: 157, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0157_f00_s0.png", nome: "Typhlosion", tipo: "Fogo"},
        {dex: 158, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0158_f00_s0.png", nome: "Totodile", tipo: "Água"},
        {dex: 159, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0159_f00_s0.png", nome: "Croconaw", tipo: "Água"},
        {dex: 160, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0160_f00_s0.png", nome: "Feraligatr", tipo: "Água"},
        {dex: 161, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0161_f00_s0.png", nome: "Sentret", tipo: "Normal"},
        {dex: 162, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0162_f00_s0.png", nome: "Furret", tipo: "Normal"},
        {dex: 163, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0163_f00_s0.png", nome: "Hoothoot", tipo: "Normal/Voador"},
        {dex: 164, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0164_f00_s0.png", nome: "Noctowl", tipo: "Normal/Voador"},
        {dex: 165, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0165_f00_s0.png", nome: "Ledyba", tipo: "Inseto/Voador"},
        {dex: 166, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0166_f00_s0.png", nome: "Ledian", tipo: "Inseto/Voador"},
        {dex: 167, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0167_f00_s0.png", nome: "Spinarak", tipo: "Inseto/Venenoso"},
        {dex: 168, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0168_f00_s0.png", nome: "Ariados", tipo: "Inseto/Venenoso"},
        {dex: 169, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0169_f00_s0.png", nome: "Crobat", tipo: "Veneno/Voador"},
        {dex: 170, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0170_f00_s0.png", nome: "Chinchou", tipo: "Água/Elétrico"},
        {dex: 171, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0171_f00_s0.png", nome: "Lanturn", tipo: "Água/Elétrico"},
        {dex: 172, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0172_f00_s0.png", nome: "Pichu", tipo: "Elétrico"},
        {dex: 173, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0173_f00_s0.png", nome: "Cleffa", tipo: "Fada"},
        {dex: 174, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0174_f00_s0.png", nome: "Igglybuff", tipo: "Normal/Fada"},
        {dex: 175, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0175_f00_s0.png", nome: "Togepi", tipo: "Fada"},
        {dex: 176, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0176_f00_s0.png", nome: "Togetic", tipo: "Fada/Voador"},
        {dex: 177, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0177_f00_s0.png", nome: "Natu", tipo: "Psíquico/Voador"},
        {dex: 178, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0178_f00_s0.png", nome: "Xatu", tipo: "Psíquico/Voador"},
        {dex: 179, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0179_f00_s0.png", nome: "Mareep", tipo: "Elétrico"},
        {dex: 180, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0180_f00_s0.png", nome: "Flaaffy", tipo: "Elétrico"},
        {dex: 181, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0181_f00_s0.png", nome: "Ampharos", tipo: "Elétrico"},
        {dex: 182, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0182_f00_s0.png", nome: "Bellossom", tipo: "Planta"},
        {dex: 183, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0183_f00_s0.png", nome: "Marill", tipo: "Água/Fada"},
        {dex: 184, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0184_f00_s0.png", nome: "Azumarill", tipo: "Água/Fada"},
        {dex: 185, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0185_f00_s0.png", nome: "Sudowoodo", tipo: "Pedra"},
        {dex: 186, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0186_f00_s0.png", nome: "Politoed", tipo: "Água"},
        {dex: 187, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0187_f00_s0.png", nome: "Hoppip", tipo: "Planta/Voador"},
        {dex: 188, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0188_f00_s0.png", nome: "Skiploom", tipo: "Planta/Voador"},
        {dex: 189, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0189_f00_s0.png", nome: "Jumpluff", tipo: "Planta/Voador"},
        {dex: 190, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0190_f00_s0.png", nome: "Aipom", tipo: "Normal"},
        {dex: 191, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0191_f00_s0.png", nome: "Sunkern", tipo: "Planta"},
        {dex: 192, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0192_f00_s0.png", nome: "Sunflora", tipo: "Planta"},
        {dex: 193, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0193_f00_s0.png", nome: "Yanma", tipo: "Inseto/Voador"},
        {dex: 194, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0194_f00_s0.png", nome: "Woobat", tipo: "Psíquico/Voador"},
        {dex: 195, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0195_f00_s0.png", nome: "Quagsire", tipo: "Água/Terra"},
        {dex: 196, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0196_f00_s0.png", nome: "Espeon", tipo: "Psíquico"},
        {dex: 197, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0197_f00_s0.png", nome: "Umbreon", tipo: "Sombrio"},
        {dex: 198, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0198_f00_s0.png", nome: "Murkrow", tipo: "Sombrio/Voador"},
        {dex: 199, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0199_f00_s0.png", nome: "Slowking", tipo: "Água/Psíquico"},
        {dex: 200, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0200_f00_s0.png", nome: "Misdreavus", tipo: "Fantasma"},
        {dex: 201, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0201_f00_s0.png", nome: "Unown", tipo: "Psíquico"},
        {dex: 202, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0202_f00_s0.png", nome: "Wobbuffet", tipo: "Psíquico"},
        {dex: 203, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0203_f00_s0.png", nome: "Girafarig", tipo: "Normal/Psíquico"},
        {dex: 204, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0204_f00_s0.png", nome: "Pineco", tipo: "Inseto"},
        {dex: 205, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0205_f00_s0.png", nome: "Forretress", tipo: "Inseto/Aço"},
        {dex: 206, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0206_f00_s0.png", nome: "Dunsparce", tipo: "Normal"},
        {dex: 207, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0207_f00_s0.png", nome: "Gligar", tipo: "Terra/Voador"},
        {dex: 208, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0208_f00_s0.png", nome: "Steelix", tipo: "Aço/Terra"},
        {dex: 209, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0209_f00_s0.png", nome: "Snubbull", tipo: "Fada"},
        {dex: 210, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0210_f00_s0.png", nome: "Granbull", tipo: "Fada"},
        {dex: 211, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0211_f00_s0.png", nome: "Qwilfish", tipo: "Água/Venenoso"},
        {dex: 212, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0212_f00_s0.png", nome: "Scizor", tipo: "Inseto/Aço"},
        {dex: 213, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0213_f00_s0.png", nome: "Shuckle", tipo: "Inseto/Rocha"},
        {dex: 214, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0214_f00_s0.png", nome: "Heracross", tipo: "Inseto/Lutador"},
        {dex: 215, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0215_f00_s0.png", nome: "Sneasel", tipo: "Sombrio/Gelo"},
        {dex: 216, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0216_f00_s0.png", nome: "Teddiursa", tipo: "Normal"},
        {dex: 217, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0217_f00_s0.png", nome: "Ursaring", tipo: "Normal"},
        {dex: 218, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0218_f00_s0.png", nome: "Slugma", tipo: "Fogo"},
        {dex: 219, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0219_f00_s0.png", nome: "Magcargo", tipo: "Fogo/Rocha"},
        {dex: 220, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0220_f00_s0.png", nome: "Swinub", tipo: "Gelo/Terra"},
        {dex: 221, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0221_f00_s0.png", nome: "Piloswine", tipo: "Gelo/Terra"},
        {dex: 222, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0222_f00_s0.png", nome: "Corsola", tipo: "Água/Rocha"},
        {dex: 223, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0223_f00_s0.png", nome: "Remoraid", tipo: "Água"},
        {dex: 224, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0224_f00_s0.png", nome: "Octillery", tipo: "Água"},
        {dex: 225, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0225_f00_s0.png", nome: "Delibird", tipo: "Gelo/Voador"},
        {dex: 226, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0226_f00_s0.png", nome: "Mantine", tipo: "Água/Voador"},
        {dex: 227, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0227_f00_s0.png", nome: "Skarmory", tipo: "Aço/Voador"},
        {dex: 228, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0228_f00_s0.png", nome: "Houndour", tipo: "Sombrio/Fogo"},
        {dex: 229, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0229_f00_s0.png", nome: "Houndoom", tipo: "Sombrio/Fogo"},
        {dex: 230, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0230_f00_s0.png", nome: "Kingdra", tipo: "Água/Dragão"},
        {dex: 231, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0231_f00_s0.png", nome: "Phanpy", tipo: "Terra"},
        {dex: 232, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0232_f00_s0.png", nome: "Donphan", tipo: "Terra"},
        {dex: 233, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0233_f00_s0.png", nome: "Porygon2", tipo: "Normal"},
        {dex: 234, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0234_f00_s0.png", nome: "Stantler", tipo: "Normal"},
        {dex: 235, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0235_f00_s0.png", nome: "Smeargle", tipo: "Normal"},
        {dex: 236, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0236_f00_s0.png", nome: "Tyrogue", tipo: "Lutador"},
        {dex: 237, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0237_f00_s0.png", nome: "Hitmontop", tipo: "Lutador"},
        {dex: 238, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0238_f00_s0.png", nome: "Smoochum", tipo: "Gelo/Psíquico"},
        {dex: 239, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0239_f00_s0.png", nome: "Elekid", tipo: "Elétrico"},
        {dex: 240, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0240_f00_s0.png", nome: "Magby", tipo: "Fogo"},
        {dex: 241, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0241_f00_s0.png", nome: "Miltank", tipo: "Normal"},
        {dex: 242, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0242_f00_s0.png", nome: "Blissey", tipo: "Normal"},
        {dex: 243, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0243_f00_s0.png", nome: "Raikou", tipo: "Elétrico"},
        {dex: 244, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0244_f00_s0.png", nome: "Entei", tipo: "Fogo"},
        {dex: 245, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0245_f00_s0.png", nome: "Suicune", tipo: "Água"},
        {dex: 246, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0246_f00_s0.png", nome: "Larvitar", tipo: "Pedra/Terra"},
        {dex: 247, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0247_f00_s0.png", nome: "Pupitar", tipo: "Pedra/Terra"},
        {dex: 248, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0248_f00_s0.png", nome: "Tyranitar", tipo: "Pedra/Sombrio"},
        {dex: 249, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0249_f00_s0.png", nome: "Lugia", tipo: "Psíquico/Voador"},
        {dex: 250, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0250_f00_s0.png", nome: "Ho-Oh", tipo: "Fogo/Voador"},
        {dex: 251, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0251_f00_s0.png", nome: "Celebi", tipo: "Psíquico/Planta"}
    ]
    res.render("gen2",{
        pokemon2 : pokemon2
    })
})

export default route;