import express from 'express';
const route = express.Router();

route.get("/gen4",function(req,res){
    const pokemon4 = [
        {dex: 387, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0387_f00_s0.png", nome: "Turtwig", tipo: "Planta"},
        {dex: 388, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0388_f00_s0.png", nome: "Grotle", tipo: "Planta"},
        {dex: 389, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0389_f00_s0.png", nome: "Torterra", tipo: "Planta/Terra"},
        {dex: 390, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0390_f00_s0.png", nome: "Chimchar", tipo: "Fogo"},
        {dex: 391, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0391_f00_s0.png", nome: "Monferno", tipo: "Fogo/Lutador"},
        {dex: 392, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0392_f00_s0.png", nome: "Infernape", tipo: "Fogo/Lutador"},
        {dex: 393, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0393_f00_s0.png", nome: "Piplup", tipo: "Água"},
        {dex: 394, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0394_f00_s0.png", nome: "Prinplup", tipo: "Água"},
        {dex: 395, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0395_f00_s0.png", nome: "Empoleon", tipo: "Água/Aço"},
        {dex: 396, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0396_f00_s0.png", nome: "Starly", tipo: "Normal/Voador"},
        {dex: 397, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0397_f00_s0.png", nome: "Staravia", tipo: "Normal/Voador"},
        {dex: 398, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0398_f00_s0.png", nome: "Staraptor", tipo: "Normal/Voador"},
        {dex: 399, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0399_f00_s0.png", nome: "Bidoof", tipo: "Normal"},
        {dex: 400, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0400_f00_s0.png", nome: "Bibarel", tipo: "Normal/Água"},
        {dex: 401, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0401_f00_s0.png", nome: "Kricketot", tipo: "Inseto"},
        {dex: 402, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0402_f00_s0.png", nome: "Kricketune", tipo: "Inseto"},
        {dex: 403, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0403_f00_s0.png", nome: "Shinx", tipo: "Elétrico"},
        {dex: 404, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0404_f00_s0.png", nome: "Luxio", tipo: "Elétrico"},
        {dex: 405, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0405_f00_s0.png", nome: "Luxray", tipo: "Elétrico"},
        {dex: 406, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0406_f00_s0.png", nome: "Budew", tipo: "Planta/Venenoso"},
        {dex: 407, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0407_f00_s0.png", nome: "Roserade", tipo: "Planta/Venenoso"},
        {dex: 408, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0408_f00_s0.png", nome: "Cranidos", tipo: "Pedra"},
        {dex: 409, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0409_f00_s0.png", nome: "Rampardos", tipo: "Pedra"},
        {dex: 410, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0410_f00_s0.png", nome: "Shieldon", tipo: "Pedra/Aço"},
        {dex: 411, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0411_f00_s0.png", nome: "Bastiodon", tipo: "Pedra/Aço"},
        {dex: 412, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0412_f00_s0.png", nome: "Burmy", tipo: "Inseto"},
        {dex: 413, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0413_f00_s0.png", nome: "Wormadam", tipo: "Inseto/Planta"},
        {dex: 414, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0414_f00_s0.png", nome: "Mothim", tipo: "Inseto/Voador"},
        {dex: 415, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0415_f00_s0.png", nome: "Combee", tipo: "Inseto/Voador"},
        {dex: 416, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0416_f00_s0.png", nome: "Vespiquen", tipo: "Inseto/Voador"},
        {dex: 417, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0417_f00_s0.png", nome: "Pachirisu", tipo: "Elétrico"},
        {dex: 418, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0418_f00_s0.png", nome: "Buizel", tipo: "Água"},
        {dex: 419, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0419_f00_s0.png", nome: "Floatzel", tipo: "Água"},
        {dex: 420, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0420_f00_s0.png", nome: "Cherubi", tipo: "Planta"},
        {dex: 421, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0421_f00_s0.png", nome: "Cherrim", tipo: "Planta"},
        {dex: 422, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0422_f00_s0.png", nome: "Shellos", tipo: "Água"},
        {dex: 423, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0423_f00_s0.png", nome: "Gastrodon", tipo: "Água/Terra"},
        {dex: 424, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0424_f00_s0.png", nome: "Ambipom", tipo: "Normal"},
        {dex: 425, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0425_f00_s0.png", nome: "Drifloon", tipo: "Fantasma/Voador"},
        {dex: 426, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0426_f00_s0.png", nome: "Drifblim", tipo: "Fantasma/Voador"},
        {dex: 427, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0427_f00_s0.png", nome: "Buneary", tipo: "Normal"},
        {dex: 428, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0428_f00_s0.png", nome: "Lopunny", tipo: "Normal"},
        {dex: 429, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0429_f00_s0.png", nome: "Mismagius", tipo: "Fantasma"},
        {dex: 430, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0430_f00_s0.png", nome: "Honchkrow", tipo: "Sombrio/Voador"},
        {dex: 431, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0431_f00_s0.png", nome: "Glameow", tipo: "Normal"},
        {dex: 432, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0432_f00_s0.png", nome: "Purugly", tipo: "Normal"},
        {dex: 433, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0433_f00_s0.png", nome: "Chingling", tipo: "Psíquico"},
        {dex: 434, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0434_f00_s0.png", nome: "Stunky", tipo: "Veneno/Sombrio"},
        {dex: 435, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0435_f00_s0.png", nome: "Skuntank", tipo: "Veneno/Sombrio"},
        {dex: 436, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0436_f00_s0.png", nome: "Bronzor", tipo: "Aço/Psíquico"},
        {dex: 437, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0437_f00_s0.png", nome: "Bronzong", tipo: "Aço/Psíquico"},
        {dex: 438, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0438_f00_s0.png", nome: "Bonsly", tipo: "Pedra"},
        {dex: 439, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0439_f00_s0.png", nome: "Mime Jr.", tipo: "Psíquico/Fada"},
        {dex: 440, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0440_f00_s0.png", nome: "Happiny", tipo: "Normal"},
        {dex: 441, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0441_f00_s0.png", nome: "Chatot", tipo: "Normal/Voador"},
        {dex: 442, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0442_f00_s0.png", nome: "Spiritomb", tipo: "Fantasma/Sombrio"},
        {dex: 443, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0443_f00_s0.png", nome: "Gible", tipo: "Dragão/Terra"},
        {dex: 444, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0444_f00_s0.png", nome: "Gabite", tipo: "Dragão/Terra"},
        {dex: 445, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0445_f00_s0.png", nome: "Garchomp", tipo: "Dragão/Terra"},
        {dex: 446, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0446_f00_s0.png", nome: "Munchlax", tipo: "Normal"},
        {dex: 447, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0447_f00_s0.png", nome: "Riolu", tipo: "Lutador"},
        {dex: 448, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0448_f00_s0.png", nome: "Lucario", tipo: "Lutador/Aço"},
        {dex: 449, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0449_f00_s0.png", nome: "Hippopotas", tipo: "Terra"},
        {dex: 450, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0450_f00_s0.png", nome: "Hippowdon", tipo: "Terra"},
        {dex: 451, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0451_f00_s0.png", nome: "Skorupi", tipo: "Inseto/Venenoso"},
        {dex: 452, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0452_f00_s0.png", nome: "Drapion", tipo: "Veneno/Sombrio"},
        {dex: 453, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0453_f00_s0.png", nome: "Croagunk", tipo: "Veneno/Lutador"},
        {dex: 454, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0454_f00_s0.png", nome: "Toxicroak", tipo: "Veneno/Lutador"},
        {dex: 455, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0455_f00_s0.png", nome: "Carnivine", tipo: "Planta"},
        {dex: 456, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0456_f00_s0.png", nome: "Finneon", tipo: "Água"},
        {dex: 457, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0457_f00_s0.png", nome: "Lumineon", tipo: "Água"},
        {dex: 458, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0458_f00_s0.png", nome: "Mantyke", tipo: "Água/Voador"},
        {dex: 459, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0459_f00_s0.png", nome: "Snover", tipo: "Planta/Gelo"},
        {dex: 460, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0460_f00_s0.png", nome: "Abomasnow", tipo: "Planta/Gelo"},
        {dex: 461, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0461_f00_s0.png", nome: "Weavile", tipo: "Sombrio/Gelo"},
        {dex: 462, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0462_f00_s0.png", nome: "Magnezone", tipo: "Elétrico/Aço"},
        {dex: 463, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0463_f00_s0.png", nome: "Lickilicky", tipo: "Normal"},
        {dex: 464, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0464_f00_s0.png", nome: "Rhyperior", tipo: "Terra/Pedra"},
        {dex: 465, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0465_f00_s0.png", nome: "Tangrowth", tipo: "Planta"},
        {dex: 466, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0466_f00_s0.png", nome: "Electivire", tipo: "Elétrico"},
        {dex: 467, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0467_f00_s0.png", nome: "Magmortar", tipo: "Fogo"},
        {dex: 468, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0468_f00_s0.png", nome: "Togekiss", tipo: "Fada/Voador"},
        {dex: 469, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0469_f00_s0.png", nome: "Yanmega", tipo: "Inseto/Voador"},
        {dex: 470, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0470_f00_s0.png", nome: "Leafeon", tipo: "Planta"},
        {dex: 471, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0471_f00_s0.png", nome: "Glaceon", tipo: "Gelo"},
        {dex: 472, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0472_f00_s0.png", nome: "Gliscor", tipo: "Terra/Voador"},
        {dex: 473, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0473_f00_s0.png", nome: "Mamoswine", tipo: "Gelo/Terra"},
        {dex: 474, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0474_f00_s0.png", nome: "Porygon-Z", tipo: "Normal"},
        {dex: 475, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0475_f00_s0.png", nome: "Gallade", tipo: "Psíquico/Lutador"},
        {dex: 476, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0476_f00_s0.png", nome: "Probopass", tipo: "Pedra/Aço"},
        {dex: 477, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0477_f00_s0.png", nome: "Dusknoir", tipo: "Fantasma"},
        {dex: 478, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0478_f00_s0.png", nome: "Froslass", tipo: "Gelo/Fantasma"},
        {dex: 479, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0479_f00_s0.png", nome: "Rotom", tipo: "Elétrico/Fantasma"},
        {dex: 480, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0480_f00_s0.png", nome: "Uxie", tipo: "Psíquico"},
        {dex: 481, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0481_f00_s0.png", nome: "Mesprit", tipo: "Psíquico"},
        {dex: 482, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0482_f00_s0.png", nome: "Azelf", tipo: "Psíquico"},
        {dex: 483, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0483_f00_s0.png", nome: "Dialga", tipo: "Aço/Dragão"},
        {dex: 484, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0484_f00_s0.png", nome: "Palkia", tipo: "Água/Dragão"},
        {dex: 485, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0485_f00_s0.png", nome: "Heatran", tipo: "Fogo/Aço"},
        {dex: 486, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0486_f00_s0.png", nome: "Regigigas", tipo: "Normal"},
        {dex: 487, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0487_f00_s0.png", nome: "Giratina", tipo: "Fantasma/Dragão"},
        {dex: 488, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0488_f00_s0.png", nome: "Cresselia", tipo: "Psíquico"},
        {dex: 489, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0489_f00_s0.png", nome: "Phione", tipo: "Água"},
        {dex: 490, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0490_f00_s0.png", nome: "Manaphy", tipo: "Água"},
        {dex: 491, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0491_f00_s0.png", nome: "Darkrai", tipo: "Sombrio"},
        {dex: 492, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0492_f00_s0.png", nome: "Shaymin", tipo: "Planta"},
        {dex: 493, img: "https://resource.pokemon-home.com/battledata/img/pokei128/icon0493_f00_s0.png", nome: "Arceus", tipo: "Normal"}
    ]
    res.render("gen4",{
        pokemon4 : pokemon4
    })
})

export default route;